version: '3.1'

services:

  elasticsearch:
    image: elasticsearch
  kibana:
    image: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:alpine
    volumes:
      - /Users/imac/personalproject/elasticsearch:/config-dir
    depends_on:
      - elasticsearch